export const products = [
  {
    id: 1,
    title: "puma 350",
    price: "2500",
    description: "importadas desde usa",
    category: "deportivas",
    stock: 5,
    img: "https://res.cloudinary.com/dkhpws3ib/image/upload/v1686700110/cld-sample-3.jpg",
  },
  {
    id: 2,
    title: "puma 335",
    price: "2800",
    description: "importadas desde usa",
    category: "deportivas",
    stock:3,
    img: "https://res.cloudinary.com/dkhpws3ib/image/upload/v1686700109/cld-sample.jpg",
  },
  {
    id: 3,
    title: " polo 254",
    price: "2800",
    description: "importadas desde usa",
    category: "formal",
    stock:2,
    img: "https://res.cloudinary.com/dkhpws3ib/image/upload/v1686700095/samples/ecommerce/leather-bag-gray.jpg",
  },
  {
    id: 4,
    title: " polo 285",
    price: "2452",
    description: "importadas desde usa",
    category: "formal",
    stock:6,
    img: "https://res.cloudinary.com/dkhpws3ib/image/upload/v1686700093/samples/people/bicycle.jpg",
  },
];
